name: Frontend deployment

on:
  push:
    branches:
      - frontend-prod
  pull_request:
    branches:
      - frontend-prod
    types: [closed]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Frontend deployment
      run: |
        TOKEN="tKhXbcqYpicDLKbJ8kapKbZ"
        URL="https://admin.kehillos.com/deploy/?type=frontend"
        curl -X POST $URL -H "Authorization: Token $TOKEN"
